version: '3.5'
services:

  postgres:
    restart: always
    image: rspark-postgres
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"     # Postgres
      
  hadoop:
    restart: always
    image: rspark-hadoop
    container_name: hadoop
    hostname: hadoop
    ports:
      - "9000:9000"     # Hadoop
      - "50070:50070"   # Hadoop UI
      
  hive:
    restart: always
    image: rspark-hive
    container_name: hive
    hostname: hive
    ports:
      - "10000:10000"
    depends_on:
      - hadoop
      - postgres
      
  rstudio:
    restart: always
    image: rspark-rstudio
    container_name: rstudio
    hostname: rstudio
    environment:
      - PASSWORD=rstudiojh
    ports:
      - "8787:8787"     # RStudio UI
    depends_on: 
      - hadoop
      - hive
